# docker run -d -p 8081:8081 -v /path/to/downloads:/downloads ghcr.io/alexta69/metube

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"    # Qdrant API
    #   - "6334:6334"    # (optional) Qdrant Web UI
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/qdrant_data:/qdrant/storage

  # ingestion:
  #   build: .
  #   restart: unless-stopped
  #   depends_on:
  #     - qdrant
  #   volumes:
  #     - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/docs:/docs    # Mount local docs folder
  #   environment:
  #     - LOGLEVEL=$LOGLEVEL
  #     - QDRANT_HOST=$QDRANT_HOST
  #     - QDRANT_PORT=$QDRANT_PORT
  #     - OPENAI_API_KEY=$OPENAI_API_KEY
  #     - DOCS_PATH=$DOCS_PATH
  #     - COLLECTION_NAME=$COLLECTION_NAME
  #     - EMBEDDING_MODEL=$EMBEDDING_MODEL
  #     - CHUNK_SIZE=$CHUNK_SIZE
  #     - CHUNK_OVERLAP=$CHUNK_OVERLAP

  ui:
    image: ghcr.io/cinnamon/kotaemon:main-ollama
    restart: unless-stopped
    # ports:
    #   - "5000:5000"    # Web UI port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KH_VECTORSTORE=Qdrant
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.service=$COMPOSE_PROJECT_NAME"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=5000"

  #     - "homepage.group=$HOME_GROUP"
  #     - "homepage.name=$HOME_NAME"
  #     - "homepage.icon=$HOME_ICON"
  #     - "homepage.href=https://$HOST"
  #     - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK

