services:
  douceville:
    image: ydethe/douceville:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      addok:
        condition: service_started
    environment:
      - LOGFIRE_TOKEN=$LOGFIRE_TOKEN
      - LOGLEVEL=$LOGLEVEL
      - OPENROUTESERVICE_KEY=$OPENROUTESERVICE_KEY
      - POSTGRES_HOST=$POSTGRES_HOST
      - ADDOK_HOST=$ADDOK_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - API_PATH=$API_PATH
      - NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
      - SUPABASE_TEST_USER=$SUPABASE_TEST_USER
      - SUPABASE_TEST_PASSWORD=$SUPABASE_TEST_PASSWORD
      - SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET
      - SUPABASE_ADMIN_KEY=$SUPABASE_ADMIN_KEY
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/code
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3566"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

  db:
    image: postgis/postgis
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data
    environment:
      TZ: $TZ
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
